Update 09-functions.yaml

diff --git a/.github/workflows/09-functions.yaml b/.github/workflows/09-functions.yaml
--- a/.github/workflows/09-functions.yaml
+++ b/.github/workflows/09-functions.yaml
@@ -9,20 +9,16 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Failing step
-        run: |
-          exit 1
+        run: exit 1   
       - name: I will be skipped
         if: ${{ success() }}
-        run: |
-          echo "I will print if previous steps succeed."
+        run: echo "I will print if previous steps succeed."
       - name: I will execute
-        run: |
-          echo "I will print if any previous step fails."
+        if: ${{ failure() }}
+        run: echo "I will print if any previous step fails."        
       - name: I will execute
-        if: ${{ ! cancelled() }}
-        run: |
-          echo "I will always print, except when the workflow is cancelled."
+        if: ${{ !cancelled() }}
+        run: echo "I will always print, except when the workflow is cancelled."   
       - name: I will execute when cancelled
         if: ${{ cancelled }}
-        run: |
-          echo "I will execute when cancelled"
+        run: echo "I will execute when cancelled"
